version: "2"

## To use this Docker image, you can use
## make nginx-extras from Makefile in this repository
## then execute this using docker-compose
##
## ```
## make nginx-extras
## dc up -d
## ```
##
## Then you can tail the logs from inside the container
##
## ```
## tail -f logs/error.log logs/access.log
## ```
services:
  nginx:
    image: nginx-extras
    ports:
        - "80:80"
    environment:
        - NGINX_HOST=webplatform.org
        - NGINX_PORT=80
    volumes:
        - "./build:/usr/share/nginx/html:ro"
        - "./config/nginx-server.conf:/etc/nginx/sites-enabled/default:ro"
        - "./config/nginx:/etc/nginx/docs:ro"
        - "./logs:/var/log/nginx"
